name: Release

on:
  push:
    tags:
      - 'v*.*.*'

# Grant the workflow permission to create releases and upload assets
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build web
        run: npm run build:web
      - name: List build directory (debug)
        run: |
          echo "Listing build/ contents"
          ls -la build || true
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release triggered from tag ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release asset (if present)
        if: always()
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/frontend-prototype.html
          asset_name: frontend-prototype.html
          asset_content_type: text/html
      - name: Show release URL
        if: always()
        run: |
          echo "Release created: ${{ steps.create_release.outputs.html_url }}"
